/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyOtpImport } from './routes/verify-otp'
import { Route as SignupImport } from './routes/signup'
import { Route as SignoutImport } from './routes/signout'
import { Route as SigninImport } from './routes/signin'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as LeadsIndexImport } from './routes/leads/index'
import { Route as SessionsTwoFactorAppImport } from './routes/sessions/two-factor/app'
import { Route as SettingsSecurityTwoFactorIndexImport } from './routes/settings/security/two-factor/index'

// Create/Update Routes

const VerifyOtpRoute = VerifyOtpImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeadsIndexRoute = LeadsIndexImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRoute,
} as any)

const SessionsTwoFactorAppRoute = SessionsTwoFactorAppImport.update({
  id: '/sessions/two-factor/app',
  path: '/sessions/two-factor/app',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSecurityTwoFactorIndexRoute =
  SettingsSecurityTwoFactorIndexImport.update({
    id: '/settings/security/two-factor/',
    path: '/settings/security/two-factor/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpImport
      parentRoute: typeof rootRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sessions/two-factor/app': {
      id: '/sessions/two-factor/app'
      path: '/sessions/two-factor/app'
      fullPath: '/sessions/two-factor/app'
      preLoaderRoute: typeof SessionsTwoFactorAppImport
      parentRoute: typeof rootRoute
    }
    '/settings/security/two-factor/': {
      id: '/settings/security/two-factor/'
      path: '/settings/security/two-factor'
      fullPath: '/settings/security/two-factor'
      preLoaderRoute: typeof SettingsSecurityTwoFactorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/leads': typeof LeadsIndexRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/settings/security/two-factor': typeof SettingsSecurityTwoFactorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/leads': typeof LeadsIndexRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/settings/security/two-factor': typeof SettingsSecurityTwoFactorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/leads/': typeof LeadsIndexRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/settings/security/two-factor/': typeof SettingsSecurityTwoFactorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verify-otp'
    | '/leads'
    | '/sessions/two-factor/app'
    | '/settings/security/two-factor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verify-otp'
    | '/leads'
    | '/sessions/two-factor/app'
    | '/settings/security/two-factor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verify-otp'
    | '/leads/'
    | '/sessions/two-factor/app'
    | '/settings/security/two-factor/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  SessionsTwoFactorAppRoute: typeof SessionsTwoFactorAppRoute
  SettingsSecurityTwoFactorIndexRoute: typeof SettingsSecurityTwoFactorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  SessionsTwoFactorAppRoute: SessionsTwoFactorAppRoute,
  SettingsSecurityTwoFactorIndexRoute: SettingsSecurityTwoFactorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/forgot-password",
        "/reset-password",
        "/signin",
        "/signout",
        "/signup",
        "/verify-otp",
        "/leads/",
        "/sessions/two-factor/app",
        "/settings/security/two-factor/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/verify-otp": {
      "filePath": "verify-otp.tsx"
    },
    "/leads/": {
      "filePath": "leads/index.tsx"
    },
    "/sessions/two-factor/app": {
      "filePath": "sessions/two-factor/app.tsx"
    },
    "/settings/security/two-factor/": {
      "filePath": "settings/security/two-factor/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
